var frame_Options = [
    { "frame_Text" : "프레임을 선택하세요", "frame_Value" : "NULL" },
    { "frame_Text" : "샤이닝 스타", "frame_Value" : "U1" },
    { "frame_Text" : "응축된 암흑의 광휘", "frame_Value" : "R1" },
    { "frame_Text" : "사이버네틱", "frame_Value" : "R2" },
    { "frame_Text" : "지고의 날개", "frame_Value" : "R3" },
    { "frame_Text" : "칠흑의 날개", "frame_Value" : "R4" },
    { "frame_Text" : "드래고니안", "frame_Value" : "R5" },
    { "frame_Text" : "종합 전투력 주간 1위", "frame_Value" : "TCP_1" },
    { "frame_Text" : "종합 전투력 주간 2위", "frame_Value" : "TCP_2" },
    { "frame_Text" : "종합 전투력 주간 5위", "frame_Value" : "TCP_3" },
    { "frame_Text" : "종합 전투력 주간 10위", "frame_Value" : "TCP_4" },
    { "frame_Text" : "유니온 아레나 주간 1등", "frame_Value" : "UA_1" },
    { "frame_Text" : "유니온 아레나 주간 2등", "frame_Value" : "UA_2" },
    { "frame_Text" : "유니온 아레나 주간 3등", "frame_Value" : "UA_3" },
    { "frame_Text" : "유니온 아레나 주간 30등", "frame_Value" : "UA_4" },
    { "frame_Text" : "유니온 아레나 주간 100등", "frame_Value" : "UA_5" },
    { "frame_Text" : "오염 정화자 - 요드", "frame_Value" : "PURIFICATION_1" },
    { "frame_Text" : "오염 정화자 - 하르파스", "frame_Value" : "PURIFICATION_2" },
    { "frame_Text" : "오염 정화자 - 틴달로스", "frame_Value" : "PURIFICATION_3" },
    { "frame_Text" : "인류의 수호자", "frame_Value" : "PURIFICATION_4" },
    { "frame_Text" : "태스크포스 : 베테라누스", "frame_Value" : "TF_1" },
    { "frame_Text" : "태스크포스 : 소드&걸스", "frame_Value" : "TF_2" },
    { "frame_Text" : "태스크포스 : T.리벨리온", "frame_Value" : "TF_3" },
    { "frame_Text" : "태스크포스 : 좋은 친구들", "frame_Value" : "TF_4" },
    { "frame_Text" : "태스크포스 : 퀸 오브 하트", "frame_Value" : "TF_5" },
    { "frame_Text" : "곰돌이랜드", "frame_Value" : "GREMORY" },
    { "frame_Text" : "몽환세계의 쌍둥이", "frame_Value" : "DREAM_1" },
    { "frame_Text" : "몽환세계의 주인", "frame_Value" : "DREAM_2" },
    { "frame_Text" : "승리의 미용사들", "frame_Value" : "DOGRA_1" },
    { "frame_Text" : "승리의 재단사들", "frame_Value" : "MAGRA_1" },
    { "frame_Text" : "디바인배틀 : 언니최고", "frame_Value" : "DOGRA_2" },
    { "frame_Text" : "디바인배틀 : 동생좋아", "frame_Value" : "MAGRA_2" },
    { "frame_Text" : "디바인배틀 : 공룡최고", "frame_Value" : "DOGRA_3" },
    { "frame_Text" : "디바인배틀 : 로봇좋아", "frame_Value" : "MAGRA_3" },
    { "frame_Text" : "디바인배틀 : 메이드의 주인", "frame_Value" : "DOGRA_4" },
    { "frame_Text" : "디바인배틀 : 부탁해요 선생님", "frame_Value" : "MAGRA_4" },
    { "frame_Text" : "디바인배틀 : 트윈테일즈", "frame_Value" : "DOGRA_5" },
    { "frame_Text" : "디바인배틀 : 포니테일즈", "frame_Value" : "MAGRA_5" },
    { "frame_Text" : "디바인배틀 : 이과 할래", "frame_Value" : "DOGRA_6" },
    { "frame_Text" : "디바인배틀 : 문과 하자", "frame_Value" : "MAGRA_6" },
    { "frame_Text" : "디바인배틀 : SF 탐사대", "frame_Value" : "DOGRA_7" },
    { "frame_Text" : "디바인배틀 : 판타지 모험가", "frame_Value" : "MAGRA_7" },
    { "frame_Text" : "디바인배틀 : 고고한 사람", "frame_Value" : "DOGRA_8" },
    { "frame_Text" : "디바인배틀 : 파티의 히어로", "frame_Value" : "MAGRA_8" },
    { "frame_Text" : "디바인배틀 : 바다의 화신", "frame_Value" : "DOGRA_9" },
    { "frame_Text" : "디바인배틀 : 해변의 주인공", "frame_Value" : "MAGRA_9" },
    { "frame_Text" : "디바인배틀 : 어둠의 자식", "frame_Value" : "DOGRA_10" },
    { "frame_Text" : "디바인배틀 : 빛의 아이", "frame_Value" : "MAGRA_10" },
    { "frame_Text" : "팀 챌린지 비주얼 프레임 [스페셜]", "frame_Value" : "CHALLENGE_1" },
    { "frame_Text" : "팀 챌린지 비주얼 프레임 [금]", "frame_Value" : "CHALLENGE_2" },
    { "frame_Text" : "팀 챌린지 비주얼 프레임 [은]", "frame_Value" : "CHALLENGE_3" },
    { "frame_Text" : "팀 챌린지 비주얼 프레임 [동]", "frame_Value" : "CHALLENGE_4" },
    { "frame_Text" : "2차 이벤트 라이선스", "frame_Value" : "LICENSE_2" },
    { "frame_Text" : "3차 이벤트 라이선스", "frame_Value" : "LICENSE_3" },
    { "frame_Text" : "4차 이벤트 라이선스", "frame_Value" : "LICENSE_4" },
    { "frame_Text" : "2019 할로윈 이벤트 라이선스", "frame_Value" : "LICENSE_5" },
    { "frame_Text" : "6차 이벤트 라이선스", "frame_Value" : "LICENSE_6" },
    { "frame_Text" : "6차 이벤트 라이선스[프리미엄]", "frame_Value" : "LICENSE_PREMIUM_6" },
    { "frame_Text" : "대단한 서클의 비주얼 프레임", "frame_Value" : "CIRCLE" },
    { "frame_Text" : "네코제 이벤트 비주얼 프레임", "frame_Value" : "NECOJE" },
    { "frame_Text" : "신년 이벤트", "frame_Value" : "NEWYEAR" },
    { "frame_Text" : "만우절 이벤트", "frame_Value" : "APRIL" },
    { "frame_Text" : "2018 여름 이벤트", "frame_Value" : "2018SUMMER" },
    { "frame_Text" : "할로윈 이벤트", "frame_Value" : "HALLOWEEN" },
    { "frame_Text" : "스캐빈 전대 레드", "frame_Value" : "SCAVENGER_1" },
    { "frame_Text" : "스캐빈 전대 블루", "frame_Value" : "SCAVENGER_2" },
    { "frame_Text" : "스캐빈 전대 그린", "frame_Value" : "SCAVENGER_3" },
    { "frame_Text" : "스캐빈 전대 핑크", "frame_Value" : "SCAVENGER_4" },
    { "frame_Text" : "스캐빈 전대 옐로", "frame_Value" : "SCAVENGER_5" },
    { "frame_Text" : "클로저시", "frame_Value" : "POEM" },
    { "frame_Text" : "AQUA", "frame_Value" : "ACH_1" },
    { "frame_Text" : "IGNIS", "frame_Value" : "ACH_2" },
    { "frame_Text" : "VENTUS", "frame_Value" : "ACH_3" },
    { "frame_Text" : "TERRA", "frame_Value" : "ACH_4" },
    { "frame_Text" : "부산행 이벤트", "frame_Value" : "BUSAN" },
    { "frame_Text" : "대나무숲 이벤트", "frame_Value" : "BAMBOO" },
    { "frame_Text" : "국제 연금술 협회원", "frame_Value" : "ALCHEMY_1" },
    { "frame_Text" : "국제 연금술 협회장", "frame_Value" : "ALCHEMY_2" },
    { "frame_Text" : "CLOSERS ASSEMBLE", "frame_Value" : "ASSEMBLE" },
    { "frame_Text" : "CLOSERS ART BOOK", "frame_Value" : "ARTBOOK" }
    ]